# Generated by Django 5.2.3 on 2025-10-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_supplier'),
        ('projects', '0003_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supplier', verbose_name='Supplier/Shop'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='expense_type',
            field=models.CharField(choices=[('materials', 'Materials'), ('vehicle_rent', 'Vehicle Rent'), ('equipment_rent', 'Equipment Rent'), ('food_beverages', 'Food & Beverages')], max_length=50),
        ),
    ]
