# Generated by Django 5.2.3 on 2025-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(help_text="e.g., 'piece', 'kg', 'meter'", max_length=50)),
                ('initial_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Initial Quantity (Count)')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Left')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Unit')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Get a warning when stock drops to this level.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
