# Generated by Django 5.2.3 on 2025-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journal_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('materials', 'Materials Supplier'), ('vehicle_rent', 'Vehicle Rental'), ('equipment_rent', 'Equipment Rental'), ('food_beverages', 'Food & Beverages'), ('other', 'Other')], help_text='The main type of service this supplier provides.', max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
