# Generated by Django 5.2.3 on 2025-10-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourcedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_type', models.CharField(choices=[('own', 'Own Worker'), ('outsourced', 'Outsourced Worker')], max_length=20)),
                ('fixed_wage', models.DecimalField(decimal_places=2, default=0, help_text="Monthly salary for 'Own' workers.", max_digits=10)),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, help_text="Daily wage for 'Outsourced' workers.", max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('ot1_rate', models.DecimalField(decimal_places=2, default=0, help_text='Overtime rate per hour for normal days.', max_digits=10, verbose_name='OT1 Rate')),
                ('ot2_rate', models.DecimalField(decimal_places=2, default=0, help_text='Overtime rate per hour for holidays.', max_digits=10, verbose_name='OT2 Rate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='workers.outsourcedgroup')),
            ],
        ),
        migrations.AddField(
            model_name='outsourcedgroup',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'worker_type': 'outsourced'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_group', to='workers.worker'),
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Mark as Holiday Attendance')),
                ('is_paid', models.BooleanField(default=False, help_text='Mark this record as paid.')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('total_wage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'Worker Attendances',
                'ordering': ['-date'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
