# Generated by Django 5.2.3 on 2025-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_remove_quotation_file_quotation_status_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='Number of revisions uploaded.'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Sent)'), ('under_review', 'On Table for Approval'), ('revised', 'Revised'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
