# Generated by Django 5.2.3 on 2025-10-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_revision_count_alter_quotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='revision_count',
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotation', to='quotations.quotationfile'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'On Table for Approval'), ('revised', 'Revised'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
